### ISSUE TITLE
What are the source and target models used in Tab.7 in the paper?

### ISSUE THREAD

**Issue by GeorgeCarpenter** [hsndbk4/ARC#1]
Hi, we gonna reproduce the result in the paper. However, we don't know exactly what source and target models are used in Tab.1 since there only is one model in each row in Tab.7.

For example, for the 62.43 result in the 2nd row, what are the source model and target model to get the result? Are the source model and target model both adversarial trained?

![image](https://user-images.githubusercontent.com/107400442/219014973-c19f74e7-99b3-48c6-a8d5-77af8328bf3d.png)

Thanks.

**Comment by hsndbk4** [comment]
Hello,

Each entry refers to a white-box attack evaluation where the source and target model are the same. The single models (AT) are adversarially trained with an l_p norm-bounded adversary.
